In [1]:
from google.colab import files

uploaded = files.upload()

Saving Day10_Flight_Operations_Dataset.csv to Day10_Flight_Operations_Dataset.csv

In [2]:
import pandas as pd
df = pd.read_csv("Day10_Flight_Operations_Dataset.csv")

In [3]:
df = pd.read_csv("Day10_Flight_Operations_Dataset.csv")

In [4]:
df.head()

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3
1,FL0002,2026-06-07,Akasa Air,Delhi,Mumbai,Boeing 737,Economy,70,210,4468,0.0,On Time,Fog,Travel Agency,16,Vegan,5
2,FL0003,2026-05-12,Air India,Kochi,Delhi,Boeing 737,Economy,67,220,4713,5.0,On Time,Rain,Travel Agency,19,No Meal,2
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5

In [5]:
df.tail()

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
175,FL0176,2026-04-10,IndiGo,Ahmedabad,Bengaluru,Airbus A320,Economy,48,189,4298,0.0,On Time,Storm,Mobile App,11,Vegetarian,5
176,FL0177,2026-02-17,Vistara,Chennai,Mumbai,Airbus A320,Business,124,180,17306,20.0,Delayed,Cloudy,Mobile App,8,No Meal,5
177,FL0178,2026-04-30,IndiGo,Delhi,Mumbai,Airbus A319,Economy,112,186,4490,110.0,Delayed,Fog,Online Travel Portal,16,Vegetarian,3
178,FL0179,2026-05-08,Vistara,Bengaluru,Kochi,Airbus A320,Economy,134,189,5413,20.0,Delayed,Rain,Online Travel Portal,9,No Meal,2
179,FL0180,2026-01-22,Akasa Air,Delhi,Mumbai,Airbus A321,Economy,144,210,3767,75.0,Delayed,Fog,Online Travel Portal,17,No Meal,5

In [ ]:
df.sample(5)

### Generate statistics

In [ ]:
df.describe()

In [ ]:
df.isnull().sum()

In [ ]:
(df.isnull().sum() / len(df)) * 100

In [ ]:
df.duplicated().sum()

### Individual Columns

In [6]:
df["Origin"].unique()

array(['Mumbai', 'Delhi', 'Kochi', 'Srinagar', 'Pune', 'Ahmedabad',
       'Lucknow', 'Jaipur', 'Bengaluru', 'Chennai', 'Hyderabad'],
      dtype=object)

In [8]:
df["Airline"].unique()

array(['SpiceJet', 'Akasa Air', 'Air India', 'Air India Express',
       'Vistara', 'IndiGo'], dtype=object)

Data Selection

In [ ]:
df["Airline"]

In [9]:
df[["Origin", "Destination"]]

        Origin Destination
0       Mumbai   Bengaluru
1        Delhi      Mumbai
2        Kochi       Delhi
3     Srinagar       Delhi
4         Pune       Delhi
..         ...         ...
175  Ahmedabad   Bengaluru
176    Chennai      Mumbai
177      Delhi      Mumbai
178  Bengaluru       Kochi
179      Delhi      Mumbai

[180 rows x 2 columns]

Flitering

In [ ]:
df[df["Flight_Status"] == "Delayed"]

In [14]:
df[(df["Meal_Preference"] == "No Meal") & (df["Flight_Status"] == "Delayed")]

,Flight_ID,Flight_Date,Airline,Origin,Destination,Aircraft,Travel_Class,Passengers,Seat_Capacity,Average_Ticket_Price,Delay_Minutes,Flight_Status,Weather,Booking_Channel,Avg_Baggage_Kg,Meal_Preference,Passenger_Satisfaction
0,FL0001,2026-03-23,SpiceJet,Mumbai,Bengaluru,Airbus A319,Economy,210,180,6894,50.0,Delayed,Storm,Online Travel Portal,23,No Meal,3
3,FL0004,2026-05-30,Akasa Air,Srinagar,Delhi,Airbus A319,Economy,153,220,3791,35.0,Delayed,Storm,Travel Agency,18,No Meal,2
4,FL0005,2026-02-27,Air India,Pune,Delhi,Airbus A319,Premium Economy,178,180,6505,20.0,Delayed,Cloudy,Airline Website,25,No Meal,5
32,FL0033,2026-04-27,Akasa Air,Ahmedabad,Bengaluru,Boeing 737,Business,66,180,17625,35.0,Delayed,Cloudy,Mobile App,15,No Meal,4
42,FL0043,2026-06-19,Vistara,Delhi,Chennai,Airbus A319,Economy,64,220,4029,50.0,Delayed,Clear,Mobile App,5,No Meal,3
43,FL0044,2026-04-20,Air India Express,Bengaluru,Hyderabad,Airbus A319,Economy,176,186,3075,35.0,Delayed,Storm,Travel Agency,16,No Meal,3
53,FL0054,2026-04-11,SpiceJet,Mumbai,Bengaluru,Airbus A320,Economy,49,180,4738,20.0,Delayed,Rain,Mobile App,14,No Meal,3
58,FL0059,2026-01-10,Air India Express,Delhi,Srinagar,Airbus A319,Economy,159,220,3708,20.0,Delayed,Storm,Airline Website,11,No Meal,2
80,FL0081,2026-04-03,SpiceJet,Delhi,Mumbai,Airbus A320,Economy,199,180,2378,50.0,Delayed,Rain,Online Travel Portal,13,No Meal,4
100,FL0101,2026-05-24,IndiGo,Jaipur,Mumbai,Boeing 737,Economy,62,180,2552,50.0,Delayed,Cloudy,Airline Website,5,No Meal,2
131,FL0132,2026-02-04,Air India,Hyderabad,Kolkata,Airbus A321,Economy,61,220,3483,75.0,Delayed,Clear,Mobile App,18,No Meal,5
144,FL0145,2026-01-20,Akasa Air,Bengaluru,Hyderabad,Airbus A319,Economy,114,186,3022,20.0,Delayed,Fog,Mobile App,22,No Meal,2
159,FL0160,2026-06-23,Vistara,Lucknow,Delhi,Airbus A321,Economy,91,210,5443,75.0,Delayed,Storm,Airline Website,10,No Meal,2
168,FL0169,2026-02-10,IndiGo,Delhi,Chennai,Airbus A320,Economy,152,220,4051,35.0,Delayed,Clear,Online Travel Portal,10,No Meal,2
169,FL0170,2026-06-25,IndiGo,Mumbai,Kolkata,Airbus A319,Economy,130,180,3938,110.0,Delayed,Rain,Online Travel Portal,17,No Meal,4
172,FL0173,2026-06-02,SpiceJet,Srinagar,Delhi,Airbus A319,Economy,143,189,6817,75.0,Delayed,Storm,Mobile App,20,No Meal,2
173,FL0174,2026-04-27,Vistara,Hyderabad,Kolkata,Airbus A319,Economy,93,189,3392,50.0,Delayed,Fog,Airline Website,10,No Meal,3
176,FL0177,2026-02-17,Vistara,Chennai,Mumbai,Airbus A320,Business,124,180,17306,20.0,Delayed,Cloudy,Mobile App,8,No Meal,5
178,FL0179,2026-05-08,Vistara,Bengaluru,Kochi,Airbus A320,Economy,134,189,5413,20.0,Delayed,Rain,Online Travel Portal,9,No Meal,2
179,FL0180,2026-01-22,Akasa Air,Delhi,Mumbai,Airbus A321,Economy,144,210,3767,75.0,Delayed,Fog,Online Travel Portal,17,No Meal,5

Sorting

In [ ]:
df.sort_values("Delay_Minutes", ascending=False)

### Grouping

In [17]:
df.groupby("Airline")["Passengers"].sum()

Airline
Air India            3074
Air India Express    3027
Akasa Air            3427
IndiGo               4158
SpiceJet             3929
Vistara              4484
Name: Passengers, dtype: int64

In [18]:
df.groupby("Airline")["Passengers"].mean()

Airline
Air India            128.083333
Air India Express    126.125000
Akasa Air            110.548387
IndiGo               129.937500
SpiceJet             122.781250
Vistara              121.189189
Name: Passengers, dtype: float64

### Aggregation

In [19]:
df.groupby("Airline")["Passengers"].agg(["sum", "mean", "min", "max", "count"])

                    sum        mean  min  max  count
Airline
Air India          3074  128.083333   45  201     24
Air India Express  3027  126.125000   57  209     24
Akasa Air          3427  110.548387   50  202     31
IndiGo             4158  129.937500   48  198     32
SpiceJet           3929  122.781250   49  210     32
Vistara            4484  121.189189   45  209     37

In [20]:
df.groupby(["Airline", "Flight_Status"]).size()

Airline            Flight_Status
Air India          Cancelled         1
                   Delayed           9
                   On Time          14
Air India Express  Delayed           6
                   On Time          18
Akasa Air          Cancelled         1
                   Delayed           8
                   On Time          22
IndiGo             Delayed          11
                   On Time          21
SpiceJet           Cancelled         3
                   Delayed          12
                   On Time          17
Vistara            Cancelled         2
                   Delayed          13
                   On Time          22
dtype: int64

### Data Transformation

In [22]:
df["Flight Duration Hours"] = df["Delay_Minutes"].apply(lambda x: x / 60)

MeaningFul questions

In [24]:
#Which airline has the highest number of flights?
df["Airline"].value_counts()

Airline
Vistara              37
SpiceJet             32
IndiGo               32
Akasa Air            31
Air India Express    24
Air India            24
Name: count, dtype: int64

In [25]:
#What is the average flight delay time for each airline?
df.groupby("Airline")["Delay_Minutes"].mean()

Airline
Air India            21.260870
Air India Express    11.291667
Akasa Air            14.400000
IndiGo               25.031250
SpiceJet             24.137931
Vistara              18.628571
Name: Delay_Minutes, dtype: float64

In [26]:
#How many flights are delayed?
df["Flight_Status"].value_counts()

Flight_Status
On Time      114
Delayed       59
Cancelled      7
Name: count, dtype: int64