In [1]:
from google.colab import files

uploaded = files.upload()

Saving Day9_Customers.csv to Day9_Customers.csv
Saving Day9_Products.csv to Day9_Products.csv
Saving Day9_Orders.csv to Day9_Orders.csv

In [3]:
import pandas as pd
orders = pd.read_csv("Day9_Orders.csv")
customers = pd.read_csv("Day9_Customers.csv")
products = pd.read_csv("Day9_Products.csv")

In [5]:
print("Orders:")
display(orders.head())

print("Customers:")
display(customers.head())

print("Products:")
display(products.head())

Orders:

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

Customers:

  Customer_ID Customer_Name      City Region Membership_Type
0        C001  Aarav Sharma  Srinagar  North         Premium
1        C002     Zoya Khan     Delhi  North         Regular
2        C003   Rohan Mehta    Mumbai   West         Premium
3        C004  Ananya Singh     Jammu  North         Regular
4        C005     Kabir Ali   Lucknow  North             New

Products:

  Product_ID         Product_Name     Category  Unit_Price     Brand
0       P001  Wireless Headphones  Electronics        1499  SoundMax
1       P002  Mechanical Keyboard  Electronics        2499    KeyPro
2       P003       Wireless Mouse  Electronics         899  TechGear
3       P004          Smart Watch  Electronics        3299   FitTech
4       P005           Power Bank  Electronics        1199  VoltPlus

In [6]:
print("Orders columns:")
print(orders.columns)

print("\nCustomers columns:")
print(customers.columns)

print("\nProducts columns:")
print(products.columns)

Orders columns:
Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity',
       'Payment_Method', 'Order_Status'],
      dtype='object')

Customers columns:
Index(['Customer_ID', 'Customer_Name', 'City', 'Region', 'Membership_Type'], dtype='object')

Products columns:
Index(['Product_ID', 'Product_Name', 'Category', 'Unit_Price', 'Brand'], dtype='object')

In [ ]:
orders.info()

In [ ]:
customers.info()

In [ ]:
products.info()

In [7]:
print("Orders shape:", orders.shape)
print("Customers shape:", customers.shape)
print("Products shape:", products.shape)

Orders shape: (120, 7)
Customers shape: (30, 5)
Products shape: (20, 5)

## Find the common columns

---

### For example

Orders

CustomerID = 101
ProductID = 5


Customers
CustomerID = 101


Products
ProductID = 5

So we can connect the information.

In [10]:
#Suppose your common column is CustomerID.
merged_data = pd.merge(
    orders,
    customers,
    on="Customer_ID",
    how="left"
)

In [12]:
#Now connect the products.
#If the common column is Product_ID:
merged_data = pd.merge(
    merged_data,
    products,
    on="Product_ID",
    how="left"
)

In [14]:
#To check
merged_data.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name_x,Category_x,Unit_Price_x,Brand_x,Product_Name_y,Category_y,Unit_Price_y,Brand_y
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew,Coffee Maker,Home & Kitchen,3499,HomeBrew

In [15]:
#And
merged_data.shape

(120, 19)

## Demonstrate concat()

concat() is used to combine DataFrames along rows or columns. Here, two sample DataFrames are combined row-wise.

Important: concat() and merge() are different.

merge()

Used when datasets have a relationship through a common column.

In [16]:
sample_orders = orders.head(5)
sample_orders_2 = orders.head(5)

combined_orders = pd.concat(
    [sample_orders, sample_orders_2],
    ignore_index=True
)

combined_orders

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered
5,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
6,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
7,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
8,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
9,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

## Convert the Order Date

In [17]:
merged_data["Order_Date"] = pd.to_datetime(
    merged_data["Order_Date"]
)

In [19]:
#To check
merged_data["Order_Date"].dtype

dtype('<M8[ns]')

In [21]:
#Extract the month
merged_data["Month"] = merged_data["Order_Date"].dt.month

In [22]:
#Extract the day
merged_data["Day"] = merged_data["Order_Date"].dt.day

In [26]:
#Extract the day of the week
merged_data["DayOfWeek"] = merged_data["Order_Date"].dt.day_name()

In [25]:
display(merged_data.head())

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,...,Category_x,Unit_Price_x,Brand_x,Product_Name_y,Category_y,Unit_Price_y,Brand_y,Month,Day,DayOfWeek
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,...,Sports,2499,BatPro,Cricket Bat,Sports,2499,BatPro,2,19,Thursday
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,...,Electronics,899,TechGear,Wireless Mouse,Electronics,899,TechGear,1,25,Sunday
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,...,Electronics,3299,FitTech,Smart Watch,Electronics,3299,FitTech,2,26,Thursday
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,...,Books,999,AIPress,Machine Learning Basics,Books,999,AIPress,3,4,Wednesday
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,...,Home & Kitchen,3499,HomeBrew,Coffee Maker,Home & Kitchen,3499,HomeBrew,3,29,Sunday

## Use apply()
One useful thing you can do is create a new column based on an existing column.

For example, if your dataset has a Price column:

In [ ]:
merged_data["Price_With_Tax"] = merged_data["Price"].apply(
    lambda x: x * 1.18
)

#This assumes an 18% tax calculation.

## Calculate a useful column

If your Products dataset contains a price and Orders contains quantity, you can create:

In [ ]:
merged_data["TotalSales"] = (
    merged_data["Quantity"] * merged_data["Price"]
)

Clean the final DataFrame

In [27]:
merged_data.isnull().sum()

Order_ID           0
Order_Date         0
Customer_ID        0
Product_ID         0
Quantity           0
Payment_Method     0
Order_Status       0
Customer_Name      0
City               0
Region             0
Membership_Type    0
Product_Name_x     0
Category_x         0
Unit_Price_x       0
Brand_x            0
Product_Name_y     0
Category_y         0
Unit_Price_y       0
Brand_y            0
Month              0
Day                0
DayOfWeek          0
dtype: int64

In [32]:
merged_data.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,...,Category_x,Unit_Price_x,Brand_x,Product_Name_y,Category_y,Unit_Price_y,Brand_y,Month,Day,DayOfWeek
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,...,Sports,2499,BatPro,Cricket Bat,Sports,2499,BatPro,2,19,Thursday
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,...,Electronics,899,TechGear,Wireless Mouse,Electronics,899,TechGear,1,25,Sunday
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,...,Electronics,3299,FitTech,Smart Watch,Electronics,3299,FitTech,2,26,Thursday
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,...,Books,999,AIPress,Machine Learning Basics,Books,999,AIPress,3,4,Wednesday
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,...,Home & Kitchen,3499,HomeBrew,Coffee Maker,Home & Kitchen,3499,HomeBrew,3,29,Sunday

In [28]:
merged_data.duplicated().sum()

np.int64(0)

In [31]:
merged_data = merged_data.drop_duplicates()

In [29]:
merged_data.duplicated().sum()

np.int64(0)

In [34]:
merged_data.to_csv(
    "processed_ecommerce_dataset.csv",
    index=False
)